package service

import (
	"bufio"
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"strconv"
	"strings"

	"github.com/miclle/litecad/internal/entity"
	"github.com/miclle/litecad/pkg/id"
	"gorm.io/gorm"
)

// ErrModelPreviewUnavailable indicates preview conversion failed or produced no mesh.
var ErrModelPreviewUnavailable = errors.New("model preview unavailable")

const (
	stepPreviewGeneratorVersion   = "step-preview-v1"
	gltfPreviewGeneratorVersion   = "gltf-preview-v1"
	stlOBJPreviewGeneratorVersion = "stl-obj-v1"
)

// ModelPreviewMesh is converted mesh data ready to persist as a preview artifact.
type ModelPreviewMesh struct {
	Format      string
	ContentType string
	Data        []byte
	VertexCount int
	FacetCount  int
}

// ProjectModelPreviewArtifact is the public shape for a derived model preview.
type ProjectModelPreviewArtifact struct {
	ID               string `json:"id"`
	ModelID          string `json:"model_id"`
	Format           string `json:"format"`
	ContentType      string `json:"content_type"`
	GeneratorVersion string `json:"generator_version"`
	ByteSize         int64  `json:"byte_size"`
	VertexCount      int    `json:"vertex_count"`
	FacetCount       int    `json:"facet_count"`
	Data             []byte `json:"-"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

// GetOrCreateProjectModelPreview returns a stored preview artifact or converts one from the STEP source.
func (s *Service) GetOrCreateProjectModelPreview(ctx context.Context, ownerUserID, projectID, modelID string) (ProjectModelPreviewArtifact, error) {
	ownerUserID = strings.TrimSpace(ownerUserID)
	projectID = strings.TrimSpace(projectID)
	modelID = strings.TrimSpace(modelID)
	if ownerUserID == "" || projectID == "" || modelID == "" {
		return ProjectModelPreviewArtifact{}, ErrProjectNotFound
	}

	var model entity.ProjectModel
	err := s.db.WithContext(ctx).
		Joins("JOIN projects ON projects.id = project_models.project_id").
		First(&model, "project_models.id = ? AND project_models.project_id = ? AND projects.owner_user_id = ?", modelID, projectID, ownerUserID).
		Error
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return ProjectModelPreviewArtifact{}, ErrProjectNotFound
		}
		return ProjectModelPreviewArtifact{}, fmt.Errorf("load project model for preview: %w", err)
	}
	if model.Format == "step" {
		return ProjectModelPreviewArtifact{}, fmt.Errorf("%w: STEP workbench preview is generated by the browser CAD kernel", ErrModelPreviewUnavailable)
	}

	var existing entity.ProjectModelPreviewArtifact
	err = s.db.WithContext(ctx).First(&existing, "model_id = ?", model.ID).Error
	if err == nil {
		expectedGeneratorVersion := modelPreviewGeneratorVersion(model.Format)
		if expectedGeneratorVersion == "" {
			return ProjectModelPreviewArtifact{}, ErrUnsupportedModelFormat
		}
		if existing.GeneratorVersion != expectedGeneratorVersion {
			return s.refreshPreviewArtifact(ctx, model, existing)
		}
		if _, ensureErr := s.ensureProjectGeometryVersion(ctx, model.ProjectID, model.ID, existing.ID); ensureErr != nil {
			return ProjectModelPreviewArtifact{}, ensureErr
		}
		return publicProjectModelPreview(existing), nil
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return ProjectModelPreviewArtifact{}, fmt.Errorf("load project model preview: %w", err)
	}

	mesh, err := s.convertModelPreviewMesh(ctx, model)
	if err != nil {
		return ProjectModelPreviewArtifact{}, err
	}

	artifactID, err := id.NewPrefixed("prv")
	if err != nil {
		return ProjectModelPreviewArtifact{}, err
	}
	artifact := entity.ProjectModelPreviewArtifact{
		ID:               artifactID,
		ModelID:          model.ID,
		Format:           mesh.Format,
		ContentType:      mesh.ContentType,
		GeneratorVersion: modelPreviewGeneratorVersion(model.Format),
		ByteSize:         int64(len(mesh.Data)),
		VertexCount:      mesh.VertexCount,
		FacetCount:       mesh.FacetCount,
		Data:             append([]byte(nil), mesh.Data...),
	}
	if err := s.db.WithContext(ctx).Create(&artifact).Error; err != nil {
		if isUniqueConstraintError(err) {
			return s.getExistingProjectModelPreview(ctx, model)
		}
		return ProjectModelPreviewArtifact{}, fmt.Errorf("store project model preview: %w", err)
	}
	if _, err := s.ensureProjectGeometryVersion(ctx, model.ProjectID, model.ID, artifact.ID); err != nil {
		return ProjectModelPreviewArtifact{}, err
	}
	return publicProjectModelPreview(artifact), nil
}

func (s *Service) getExistingProjectModelPreview(ctx context.Context, model entity.ProjectModel) (ProjectModelPreviewArtifact, error) {
	var existing entity.ProjectModelPreviewArtifact
	if err := s.db.WithContext(ctx).First(&existing, "model_id = ?", model.ID).Error; err != nil {
		return ProjectModelPreviewArtifact{}, fmt.Errorf("load concurrent project model preview: %w", err)
	}
	if _, err := s.ensureProjectGeometryVersion(ctx, model.ProjectID, model.ID, existing.ID); err != nil {
		return ProjectModelPreviewArtifact{}, err
	}
	return publicProjectModelPreview(existing), nil
}

func (s *Service) refreshPreviewArtifact(ctx context.Context, model entity.ProjectModel, artifact entity.ProjectModelPreviewArtifact) (ProjectModelPreviewArtifact, error) {
	mesh, err := s.convertModelPreviewMesh(ctx, model)
	if err != nil {
		return ProjectModelPreviewArtifact{}, err
	}
	artifact.Format = mesh.Format
	artifact.ContentType = mesh.ContentType
	artifact.GeneratorVersion = modelPreviewGeneratorVersion(model.Format)
	artifact.ByteSize = int64(len(mesh.Data))
	artifact.VertexCount = mesh.VertexCount
	artifact.FacetCount = mesh.FacetCount
	artifact.Data = append([]byte(nil), mesh.Data...)
	if err := s.db.WithContext(ctx).Save(&artifact).Error; err != nil {
		return ProjectModelPreviewArtifact{}, fmt.Errorf("refresh project model preview: %w", err)
	}
	if _, err := s.ensureProjectGeometryVersion(ctx, model.ProjectID, model.ID, artifact.ID); err != nil {
		return ProjectModelPreviewArtifact{}, err
	}
	return publicProjectModelPreview(artifact), nil
}

func (s *Service) convertModelPreviewMesh(ctx context.Context, model entity.ProjectModel) (ModelPreviewMesh, error) {
	switch model.Format {
	case "step":
		return ModelPreviewMesh{}, fmt.Errorf("%w: STEP workbench preview is generated by the browser CAD kernel", ErrModelPreviewUnavailable)
	case "glb":
		if _, err := ExtractGLBMetadata(model.SourceData); err != nil {
			return ModelPreviewMesh{}, fmt.Errorf("%w: %v", ErrModelPreviewUnavailable, err)
		}
		return ModelPreviewMesh{
			Format:      "glb",
			ContentType: "model/gltf-binary",
			Data:        append([]byte(nil), model.SourceData...),
		}, nil
	case "gltf":
		if _, err := ExtractGLTFMetadata(model.SourceData); err != nil {
			return ModelPreviewMesh{}, fmt.Errorf("%w: %v", ErrModelPreviewUnavailable, err)
		}
		return ModelPreviewMesh{
			Format:      "gltf",
			ContentType: "model/gltf+json",
			Data:        append([]byte(nil), model.SourceData...),
		}, nil
	case "stl":
		mesh, err := convertSTLToOBJPreview(model.SourceData)
		if err != nil {
			return ModelPreviewMesh{}, fmt.Errorf("%w: %v", ErrModelPreviewUnavailable, err)
		}
		return mesh, nil
	default:
		return ModelPreviewMesh{}, ErrUnsupportedModelFormat
	}
}

func modelPreviewGeneratorVersion(format string) string {
	switch format {
	case "step":
		return stepPreviewGeneratorVersion
	case "glb", "gltf":
		return gltfPreviewGeneratorVersion
	case "stl":
		return stlOBJPreviewGeneratorVersion
	default:
		return ""
	}
}

func isUniqueConstraintError(err error) bool {
	if err == nil {
		return false
	}
	message := strings.ToLower(err.Error())
	return strings.Contains(message, "unique constraint") ||
		strings.Contains(message, "duplicate key") ||
		strings.Contains(message, "duplicate entry") ||
		strings.Contains(message, "violates unique")
}

func (s *Service) ensureProjectGeometryVersion(ctx context.Context, projectID, modelID, previewArtifactID string) (ProjectGeometryVersion, error) {
	var existing entity.ProjectGeometryVersion
	err := s.db.WithContext(ctx).First(&existing, "preview_artifact_id = ?", previewArtifactID).Error
	if err == nil {
		return publicProjectGeometryVersion(existing), nil
	}
	if !errors.Is(err, gorm.ErrRecordNotFound) {
		return ProjectGeometryVersion{}, fmt.Errorf("load project geometry version: %w", err)
	}

	for attempt := 0; attempt < 5; attempt++ {
		var maxVersion int
		if err := s.db.WithContext(ctx).
			Model(&entity.ProjectGeometryVersion{}).
			Where("project_id = ?", projectID).
			Select("COALESCE(MAX(version_number), 0)").
			Scan(&maxVersion).
			Error; err != nil {
			return ProjectGeometryVersion{}, fmt.Errorf("load project geometry version number: %w", err)
		}
		versionID, err := id.NewPrefixed("geo")
		if err != nil {
			return ProjectGeometryVersion{}, err
		}
		version := entity.ProjectGeometryVersion{
			ID:                versionID,
			ProjectID:         projectID,
			SourceModelID:     modelID,
			PreviewArtifactID: previewArtifactID,
			VersionNumber:     maxVersion + 1,
			Summary:           "Preview artifact imported",
		}
		if err := s.db.WithContext(ctx).Create(&version).Error; err != nil {
			if isUniqueConstraintError(err) {
				var existing entity.ProjectGeometryVersion
				reloadErr := s.db.WithContext(ctx).First(&existing, "preview_artifact_id = ?", previewArtifactID).Error
				if reloadErr == nil {
					return publicProjectGeometryVersion(existing), nil
				}
				if !errors.Is(reloadErr, gorm.ErrRecordNotFound) {
					return ProjectGeometryVersion{}, fmt.Errorf("load concurrent project geometry version: %w", reloadErr)
				}
				continue
			}
			return ProjectGeometryVersion{}, fmt.Errorf("store project geometry version: %w", err)
		}
		return publicProjectGeometryVersion(version), nil
	}
	return ProjectGeometryVersion{}, fmt.Errorf("store project geometry version: %w", gorm.ErrDuplicatedKey)
}

func publicProjectModelPreview(artifact entity.ProjectModelPreviewArtifact) ProjectModelPreviewArtifact {
	return ProjectModelPreviewArtifact{
		ID:               artifact.ID,
		ModelID:          artifact.ModelID,
		Format:           artifact.Format,
		ContentType:      artifact.ContentType,
		GeneratorVersion: artifact.GeneratorVersion,
		ByteSize:         artifact.ByteSize,
		VertexCount:      artifact.VertexCount,
		FacetCount:       artifact.FacetCount,
		Data:             append([]byte(nil), artifact.Data...),
		CreatedAt:        artifact.CreatedAt.Format(timeFormatRFC3339),
		UpdatedAt:        artifact.UpdatedAt.Format(timeFormatRFC3339),
	}
}

func convertSTLToOBJPreview(data []byte) (ModelPreviewMesh, error) {
	triangles, err := parseSTLTriangles(data)
	if err != nil {
		return ModelPreviewMesh{}, err
	}
	var output strings.Builder
	output.WriteString("# Created by LiteCAD STL preview converter\n")
	for _, triangle := range triangles {
		for _, vertex := range triangle {
			output.WriteString("v ")
			output.WriteString(strconv.FormatFloat(float64(vertex[0]), 'f', -1, 32))
			output.WriteByte(' ')
			output.WriteString(strconv.FormatFloat(float64(vertex[1]), 'f', -1, 32))
			output.WriteByte(' ')
			output.WriteString(strconv.FormatFloat(float64(vertex[2]), 'f', -1, 32))
			output.WriteByte('\n')
		}
	}
	for index := range triangles {
		base := index*3 + 1
		output.WriteString("f ")
		output.WriteString(strconv.Itoa(base))
		output.WriteByte(' ')
		output.WriteString(strconv.Itoa(base + 1))
		output.WriteByte(' ')
		output.WriteString(strconv.Itoa(base + 2))
		output.WriteByte('\n')
	}
	obj := []byte(output.String())
	return ModelPreviewMesh{
		Format:      "obj",
		ContentType: "model/obj",
		Data:        obj,
		VertexCount: len(triangles) * 3,
		FacetCount:  len(triangles),
	}, nil
}

type stlTriangle [3][3]float32

func parseSTLTriangles(data []byte) ([]stlTriangle, error) {
	if triangles, ok := parseASCIISTLTriangles(data); ok {
		return triangles, nil
	}
	if triangles, ok := parseBinarySTLTriangles(data); ok {
		return triangles, nil
	}
	return nil, errInvalidSTLSource
}

func parseASCIISTLTriangles(data []byte) ([]stlTriangle, bool) {
	source := strings.TrimSpace(string(data))
	lowerSource := strings.ToLower(source)
	if !strings.HasPrefix(lowerSource, "solid ") || !strings.Contains(lowerSource, "facet normal") {
		return nil, false
	}
	triangles := []stlTriangle{}
	current := stlTriangle{}
	vertexIndex := 0
	scanner := bufio.NewScanner(strings.NewReader(source))
	for scanner.Scan() {
		fields := strings.Fields(scanner.Text())
		if len(fields) != 4 || strings.ToLower(fields[0]) != "vertex" {
			continue
		}
		x, errX := strconv.ParseFloat(fields[1], 32)
		y, errY := strconv.ParseFloat(fields[2], 32)
		z, errZ := strconv.ParseFloat(fields[3], 32)
		if errX != nil || errY != nil || errZ != nil {
			return nil, false
		}
		current[vertexIndex] = [3]float32{float32(x), float32(y), float32(z)}
		vertexIndex++
		if vertexIndex == 3 {
			triangles = append(triangles, current)
			current = stlTriangle{}
			vertexIndex = 0
		}
	}
	if len(triangles) == 0 || vertexIndex != 0 {
		return nil, false
	}
	return triangles, true
}

func parseBinarySTLTriangles(data []byte) ([]stlTriangle, bool) {
	if len(data) < 84 {
		return nil, false
	}
	triangleCount := int(binary.LittleEndian.Uint32(data[80:84]))
	if triangleCount <= 0 || 84+triangleCount*50 > len(data) {
		return nil, false
	}
	triangles := make([]stlTriangle, 0, triangleCount)
	reader := bytes.NewReader(data[84:])
	for index := 0; index < triangleCount; index++ {
		var normal [3]float32
		if err := binary.Read(reader, binary.LittleEndian, &normal); err != nil {
			return nil, false
		}
		var triangle stlTriangle
		for vertexIndex := 0; vertexIndex < 3; vertexIndex++ {
			if err := binary.Read(reader, binary.LittleEndian, &triangle[vertexIndex]); err != nil {
				return nil, false
			}
		}
		var attributes uint16
		if err := binary.Read(reader, binary.LittleEndian, &attributes); err != nil {
			return nil, false
		}
		triangles = append(triangles, triangle)
	}
	return triangles, true
}
